### cloudflare-dns "A"

# @curl-proxy http://localhost:9933

GET https://cloudflare-dns.com/dns-query?name=github.com&type=A HTTP/1.1
Accept: application/dns-json


### cloudflare-dns "AAAA"

# @curl-proxy http://localhost:9933

GET https://cloudflare-dns.com/dns-query?name=github.com&type=AAAA HTTP/1.1
Accept: application/dns-json


### Github: search topic

# @curl-proxy http://localhost:9933

GET https://api.github.com/search/topics?q=Neovim HTTP/1.1
Accept: application/vnd.github+json
X-Github-Api-Version: 2022-11-28
